# Generated by Django 2.0.6 on 2018-06-12 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='especialidade',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='trabalha_em',
            name='funcao',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
