# Generated by Django 2.0.6 on 2018-06-12 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0002_auto_20180611_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='cnpj_clinica',
        ),
        migrations.RemoveField(
            model_name='trabalha_em',
            name='cnpj_clinica',
        ),
        migrations.RemoveField(
            model_name='trabalha_em',
            name='cpf_profissional',
        ),
        migrations.DeleteModel(
            name='Profissional',
        ),
        migrations.DeleteModel(
            name='Trabalha_Em',
        ),
    ]
