# Generated by Django 2.0.6 on 2018-06-12 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0005_auto_20180611_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('cpf', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=45)),
                ('contato', models.CharField(max_length=45)),
                ('especialidade', models.CharField(max_length=45)),
                ('cnpj_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.Clinica')),
            ],
        ),
        migrations.CreateModel(
            name='Trabalha_Em',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(max_length=45)),
                ('cnpj_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.Clinica')),
                ('cpf_profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brain.Profissional')),
            ],
        ),
    ]
